const data = {
  products: [
    {
      _id: '1',
      name: 'Momo set',
      slug: 'momo-set',
      category: 'sets',
      imageHome: '/images/momo/momo-pink1.jpg',
      price: 490,
      brand: 'Gamclothes',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality clothes',
      countInStock: 10,
      colors: [
        { name: 'Pink', class: 'bg-pink', countInStock: 10 },
        { name: 'Brown', class: 'bg-brown', countInStock: 8 },
        { name: 'Cream', class: 'bg-cream', countInStock: 10 },
      ],
    },
    {
      _id: '2',
      name: 'Maxi Pop dress',
      slug: 'maxi-pop-dress',
      category: 'dress',
      imageHome: '/images/maxipopdress/maxipop-green1.jpg',
      price: 550,
      brand: 'Gamclothes',
      rating: 4.8,
      numReviews: 7,
      description: 'High quality clothes',
      countInStock: 10,
      colors: [
        { name: 'Green', class: 'bg-green', countInStock: 10 },
        { name: 'Violet', class: 'bg-violet', countInStock: 8 },
        { name: 'Yellow', class: 'bg-yellow', countInStock: 10 },
      ],
    },
    {
      _id: '3',
      name: 'Lanie Set',
      slug: 'lanie-set',
      category: 'sets',
      imageHome: '/images/lanie/lanie-white1.jpg',
      price: 590,
      brand: 'Gamclothes',
      rating: 4.8,
      numReviews: 7,
      description: 'High quality clothes',
      countInStock: 0,
      colors: [
        { name: 'White', class: 'bg-white', countInStock: 10 },
        { name: 'Blue', class: 'bg-blue', countInStock: 8 },
        { name: 'Violet', class: 'bg-violet', countInStock: 10 },
      ],
    },
  ],
};

export default data;
